catalogMode: prefer

ignoreWorkspaceRootCheck: true

shellEmulator: true

trustPolicy: no-downgrade
packages:
  - packages/*
  - playground
catalogs:
  cli:
    '@antfu/eslint-config': ^7.2.0
    '@antfu/ni': ^23.3.1
    automd: ^0.4.3
    bumpp: ^10.4.0
    eslint: ^9.39.2
    lint-staged: ^15.5.2
    pnpm: ^10.28.2
    publint: ^0.3.0
    simple-git-hooks: ^2.13.1
    tsdown: ^0.20.1
    tsx: ^4.21.0
    typescript: ^5.9.3
    vite: ^7.3.1
  inlined:
    '@antfu/utils': ^9.3.0
  openapi:
    openapi-specification-types: ^0.0.3
  playground:
    '@uni-helper/uni-network': ^0.23.1
    wpapi-to-swagger: ^0.1.0
  root:
    skills: ^1.3.1
    skills-manifest: ^0.2.1
  runtime:
    '@hairy/utils': ^1.47.0
    cac: ^6.7.14
    chalk: ^5.6.2
    fs-extra: ^11.3.3
    got: 11.8.6
    jiti: ^1.21.7
    knitwork-x: ^0.2.0
    ora: ^5.4.1
    p-pipe: ^3.1.0
    pascal-case: ^3.1.2
    prettier: ^2.8.8
    transliteration: ^2.6.1
    unconfig: ^0.3.13
  testing:
    vitest: ^4.0.18
  types:
    '@types/fs-extra': ^11.0.4
    '@types/node': ^22.19.7
    '@types/prettier': ^2.7.3
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
