catalogMode: prefer

ignoreWorkspaceRootCheck: true

shellEmulator: true
packages:
  - packages/*
  - playground
  - docs

patchedDependencies:
  md4w@0.2.7: patches/md4w@0.2.7.patch

catalogs:
  cli:
    '@antfu/eslint-config': ^7.2.0
    '@antfu/ni': ^23.3.1
    automd: ^0.4.3
    bumpp: ^10.4.0
    eslint: ^9.39.2
    lint-staged: ^15.5.2
    pnpm: ^10.28.2
    publint: ^0.3.0
    simple-git-hooks: ^2.13.1
    tsdown: ^0.20.1
    tsx: ^4.21.0
    typescript: ^5.9.3
    vite: ^7.3.1
  docs:
    '@vueuse/core': ^14.2.0
    nuxt: 4.3.0
    shiki: ^3.22.0
    undocs: latest
  inlined:
    '@antfu/utils': ^9.3.0
    fetchdts: ^0.1.7
  openapi:
    openapi-specification-types: ^0.3.0
  playground:
    '@uni-helper/uni-network': ^0.23.1
    axios: ^1.13.4
    wpapi-to-swagger: ^0.1.0
  root:
    skills: ^1.3.1
    skills-manifest: ^0.2.1
  runtime:
    '@clack/prompts': ^1.0.0-alpha.9
    '@hairy/utils': ^1.47.0
    c12: ^1.7.0
    chalk: ^5.6.2
    citty: ^0.2.0
    consola: ^3.4.2
    fs-extra: ^11.3.3
    jiti: ^1.21.7
    knitwork-x: ^0.2.0
    nypm: ^0.6.4
    ofetch: ^1.5.1
    p-pipe: ^3.1.0
    prettier: ^2.8.8
    scule: ^1.3.0
    transliteration: ^2.6.1
  testing:
    '@vitest/coverage-v8': 4.0.18
    vitest: ^4.0.18
  types:
    '@types/fs-extra': ^11.0.4
    '@types/node': ^22.19.7
    '@types/prettier': ^2.7.3

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - vue-demi
